version: '3'
volumes: 
    dados:
networks: 
    database:
    web:
services: 
    db:
        image: postgres:11.6
        volumes:
            # Data's Volume
            - dados:/var/lib/postgresql/data
        networks:
        - database
    api:
        image: golang:1.12
        volumes:
            - ./app:/app
        working_dir: /app
        networks: 
            - web
    nginx:
        image: nginx:1.13 # this will use the latest version of 1.13.x
        ports:
            - '80:80' # expose 80 on host and sent to 80 in container
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
        networks: 
            - web
    front:
        build: ./front
        expose:
          - 3000
        ports:
          - 3000:3000
        volumes:
          - ./web:/app
        depends_on: 
            - nginx
        networks: 
            - web

