version: '3'
volumes: 
    dados:
networks: 
    database:
    web:
services: 
    db:
        container_name: db-container
        image: postgres:11.6
        volumes:
            # Data's Volume
            - dados:/var/lib/postgresql/data
        networks:
        - database
    api:
        container_name: api-container
        image: golang:1.12
        volumes:
            - ./api:/api
        working_dir: /api
        command: bash -c "cd /api && go mod download && go run main.go"
        networks: 
            - web
    front:
        container_name: front-container
        build: ./front/build
        expose:
          - 3000
        ports:
          - 3000:80
        volumes:
          - ./front/build:/front
        networks: 
            - web
   
